steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'osrf/ros:melodic-desktop-bionic']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'osrf/ros:melodic-desktop-bionic', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'osrf/ros:melodic-desktop-bionic', '/home/ros/src/ci_build.bash']
timeout: 900s